### ISSUE TITLE
How to clone

### ISSUE THREAD

**Issue by opusoctopus** [zgramming/laravel-starter-project#1]
Kang, cara cloning project nya gimana ?
saya pakai cara umum nya g mau tampil.

**Comment by zgramming** [comment]
Untuk saat ini dokumentasi instalasinya dan spesifikasi yang dibutuhkan belum aku buat.
Tapi kalau mau coba aplikasinya, seharusnya clone seperti biasa tidak ada masalah.

1. git clone `https://github.com/zgramming/laravel-starter-project.git`
2. `composer install`
3. `cp .env.example .env` (sesuaikan database dll)
4. `php artisan key:generate`
5. `php artisan migrate:fresh --seed`
6. `php artisan serve`
7. untuk sementara bisa akses url `http://127.0.0.1:8000/setting/example`, karena masih belum selesai projectnya.
![image](https://user-images.githubusercontent.com/38829404/158332104-130a7356-566a-447d-a683-2d249d1ad561.png)

**Comment by opusoctopus** [comment]
makasih banyak bro, sukses!!
